### ISSUE TITLE
MovementX/Y for down and up

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerlock#15]
@RByers, @scheib
Why do we have movementX/Y set to zero for down and up events? I mean those events can have different coordinates from their last move events in general (isn't it the case?) and these attributes seem to be generic and capable of being set even when pointerlock is inactive.
So can we extend the definition to also have a correct value for down and up events?

**Comment by scheib** [comment]
I made that design decision in Pointer Lock because I want to reduce the chance of application error. All movements must be delivered to mousemove events, so applications will and can handle movement there. A naive handler would duplicate handling of delta movements if browsers did also include movement data in other events such as mousedown. The absolute positions of mouse events are not at risk of these logical  errors - worst case they would perform duplicate processing. But movementX/Y is typically used in an additive way and the values would be double counted.

**Comment by NavidZ** [comment]
Are you referring to the situation of when the pointer is locked? What if the pointer is not locked?

I don't see any guarantee in UI Event spec that mouseup coordinates should be the same as the last mousemove event that the page received. Also I didn't mean that we include the difference in both mouseup and mousemove. I meant every event will have the coordinate difference from the last dispatched event (if not unknown). So when the pointer is locked and based on the spec all the browsers will send mousemove events for all movements and all the mousedowns/ups will have the same position as the last mouse move then they ups/downs will automatically get 0 as movementX/Y. But say when the pointer is not locked and you receive a mousedown (and the last position is known) then you would get that coordinate difference in the mousedown event. How about this? Is this any better?

**Comment by scheib** [comment]
movementX/Y are defined without concern for the locked state, that isn't relevant to these concerns.

The mouse events aren't specified as precisely as they should be, but they are specified sufficiently to ensure that any movement is included in mousemove. What values might mousedown have? Deltas from the previous mousemove event, or the previous mousedown event? For anything the results in mousedown having movementX/Y != 0 applications could easily have logic errors.

Applications wishing to track delta movements should be able to be very simple, and have a handler that reads values of movementX/Y and uses it. If that handler happens to also run on other event types the logic is not brittle thanks to the specification that movementX/Y are only non-zero for mousemove events.

If we'd like clearer specification I would suggest that https://www.w3.org/TR/DOM-Level-3-Events/#events-mouseevent-event-order be clarified to indicate that mousemove events must be dispatched (as ordered in the specification) to account for all movement and that non mousemove events must therefor equal the absolute position of the previous mousemove event. Had that already been the case movementX/Y wouldn't need to have special wording to clarify that point.

Because it wasn't specified, it's unclear what implementations may be doing. But, as I mentioned for the absolute values it doesn't matter much, and for movementX/Y where it does it was specified clearly.

**Comment by NavidZ** [comment]
Alright. Fair enough. Let's go with this for now. I don't see any Blink code that sets the movementx/y only for mousemoves. But I'll do it only for pointermoves for now and see what happens.
