### ISSUE TITLE
movementX/Y when zoom in/out

### ISSUE THREAD

**Issue by EiraGe** [w3c/pointerlock#23]
movementX/Y properties is defined as movementX = eNow.screenX-ePrevious.screenX in the spec.  

Try this [test page](http://scheib.github.com/HTMLMisc/PointerLockAndFullscreen.html).
Zoom in on the page, click on the pink box to align the system cursor and the HTMLCursor. Moving mouse around without having the mouse locked, the HTML cursor will have more movement than the pointer.

The behavior is odd but it is the expected result, because HTML cursor is displayed on client coordinate but movement is on screen coordinate. 
Chrome, Edge, safari have same behavior. 

However, Firefox have movementX/Y calculated by difference in client coordinates. The cursors will remain aligned when mouse move on zoomed page.

Although this may not be a common use case of movementX/Y, but what should be the right behavior of movementX/Y? Firefox’s implement make more sense to me. The movementX/Y properties should reflect the pointer movement in client coordinates. 

Is there any reason to use screenX/Y? Should we have movementX/Y calculated base on clientX/Y instead of screenX/Y?  

@navidz @rbyers @scheib

**Comment by scheib** [comment]
I do not think the movement should be scaled based on page zoom.

The screen offers a fixed calibrated coordinate system. Users have adjusted the pointing device to operate in a reasonable way across that space. 

When a page is zoomed in the display is magnified, but the user hasn't expressed any reason to change the input. If, for example, the mouse movement is used to rotate an object then zooming a page should not change how far the object rotates for the same mechanical motion on the pointing device.

The test page you cite wasn't designed for zooming. If it was, it should take into account the zoom when displaying it's output.

Because we can't predict what clients of pointer lock are doing with input, we shouldn't scale the signal based on just one example use case (re-drawing a screen cursor). The primary motivating use case, of controlling a viewpoint in 3D, should not have input motion modified even when the page is zoomed.

**Comment by scheib** [comment]
I've updated http://scheib.github.com/HTMLMisc/PointerLockAndFullscreen.html to take zoom correctly into account. However, it's easier to look at https://scheib.github.io/HTMLMisc/PointerLockLog.html to see the movementXSum. The raw input should not change no matter DPI or page zoom setting. E.g. starting from left of screen and moving to right of screen should always produce the same input result to a web app.

**Comment by EiraGe** [comment]
Thanks for the reply.  Firefox may need to change their implement to match the spec.

But for the DPI change, the screenX/Y actually will change with device scale factor.  If movementXSum should be the same nomatter DPI, it should use system coordinate instead of screen X/Y.

**Comment by scheib** [comment]
https://github.com/w3c/pointerevents/issues/607 is discussing if screenX/Y should scale with browser zoom.

**Comment by EiraGe** [comment]
I'm closing this one as I opened w3c/uievents#42 to cover not only the zooming but also device scale.
