### ISSUE TITLE
pointerlockchange event will be sent every time mouse click event triggered

### ISSUE THREAD

**Issue by Titan-p** [w3c/pointerlock#32]
Is that a feature or a bug?
See the demo page:
`https://mdn.github.io/dom-examples/pointer-lock/`

**Comment by EiraGe** [comment]
My understanding is this is a page issue. The demo you provided has `canvas.requestPointerLock();` on click event.

Not sure whether we should add something like "if already in locked state, do nothing" since the page should already have enough information to tell whether it's in locked state or not.

**Comment by mustaqahmed** [comment]
Yes, this is a page issue!
