### ISSUE TITLE
Option needed to disable OS-level adjustment for mouse acceleration

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerlock#36]
Some games need to disable mouse acceleration to achieve a better gaming experience ([1](https://us.battle.net/forums/en/overwatch/topic/20753608843), [2](https://www.reddit.com/r/GlobalOffensive/comments/2qv4q8/why_is_mouse_acceleration_bad_for_gaming/)).

I believe this best fits in the pointerlock request api as an option to provide such a capability. [Here](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-systemparametersinfoa) is the Windows API allowing to disable that.

@smaug---- @eirage WDYT?

**Comment by EiraGe** [comment]
It sounds reasonable to me for letting developers be able to match the physical mouse movement and events movement. 
A quick search on the internet I founds it's possible for player to disable mouse acceleration on the OS (except chromeOS crbug.com/589190). Considering gaming user might like to make their own choice on mouse preference, although a bit complicate, I feel adding this is actually less important.

**Comment by NavidZ** [comment]
Is it normal for the games to have this option within them? Or do people usually go and change the settings in their platform to achieve this?

**Comment by EiraGe** [comment]
I'm not familiar with gaming area, so I have no idea how people usually do. I think changing the setting in the platform seems very complicate, so it'd be nice to have this. 
I'd also like to have more game developers' opinion to know whether this will help or not. (The cros bug has really high number of stars)

**Comment by smaug----** [comment]
I don't have enough experience on games to say what is preferred here. I would expect people to look at the platform prefs. Perhaps @juj has some feedback to this.

**Comment by scheib** [comment]
Initial specification discussions did include this topic.  The spec FAQ
summarizes as in 12.4
https://www.w3.org/TR/pointerlock/#why-bundle

In email group discussions it was raised that some games do use raw mouse
movement, before OS level adjustments.  Those adjustments are tuned to
making a relative motion pointer work well.  Other uses of mouse movement
may not work well with those same curves.  E.g. First person viewpoint
adjustment.  Further, there are also higher resolution updates for
precision aiming.

The 2011 specification selected a pragmatic choice of shipping something
that could be clearly specified and consistently implemented across
platforms.  It handles the majority of client applications -- there are
many web games using pointer lock after OS level adjustments to inputs.

See discussions in the proximity to:
https://lists.w3.org/Archives/Public/public-webapps/2011JulSep/1043.html

If there is developer demand, I personally do believe an iteration that
provides increased access to raw mouse input would be useful.

**Comment by juj** [comment]
Games do commonly provide options to users to choose mouse sensitivity, and also sometimes provide options for enabling or disabling mouse acceleration. E.g. Counter-Strike:

![steamworkshop_webupload_previewfile_126920260_preview](https://user-images.githubusercontent.com/225351/46730769-919b5300-cc91-11e8-84fb-b3c28dcba800.jpg)

MineCraft has only a sensitivity setting:

![p2j0a](https://user-images.githubusercontent.com/225351/46730540-1df94600-cc91-11e8-9bba-11cec987b885.png)

On Windows based games for example, mouse acceleration control is done by switching between [Win32 UI Mouse Events](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-mousemove) API that provides OS-level accelerated/nonlinear input, and [Raw Input API](https://docs.microsoft.com/en-us/windows/desktop/inputdev/raw-input) that provides linear unaccelerated mouse movement.

The first API reports movement taking into account user's mouse sensitivity and acceleration settings in Windows Control Panel, whereas the second API provides raw input data directly from the mouse device.

If user has disabled mouse acceleration in their Mouse control panel, then Win32 UI events report unaccelerated content, but it is rare to expect players to go manage mouse acceleration and sensitivity for individual games via control panel, hence games providing custom options.

Whether linear or nonlinear acceleration should be used for first person content or some other types of games is a highly subjective experience. E.g. some Counter-Strike players prefer to have acceleration enabled, others prefer to disable it. But both usages are common.

I would recommend here to provide an option in pointer lock to choose between raw/linear input and desktop/nonlinear input. (Recording both linear/nonlinear input data for one event passed to JS would be technically difficult to implement due to lack of coherency in the received events from the OS)

**Comment by binoculars88** [comment]
I couldn't explain it better than @juj did above.
As a game developer, I'm definitely rooting for having the option to have as raw mouse input as possible, so we can present our players with options like shown above. Certainly when it comes to releasing for both stand-alone and web, having a consistent mouse movement feel is key for us.

@scheib is there anything in the backlog that would satisfy these desires :) ?

**Comment by eliwald** [comment]
This API would be immensely useful for us. We need the ability to allow games to switch back and forth between raw (non-accelerated) input and desktop (accelerated) input as necessary, depending on the context of their game. Adding this option to the pointerlock API would unlock this use case! :)

**Comment by smaug----** [comment]
Based on some feedback, implementing this properly on all the platforms can be tricky. Linux for example has several ways to control acceleration. And I'm not sure even about MacOS.

@EiraGe @NavidZ have you figured out how to implement this everywhere per program (in such way that if a browser crashes, OS still keeps the original behavior)?

**Comment by NavidZ** [comment]
@whsieh

**Comment by scheib** [comment]
Work is underway to offer unmodified movement data: 

- Specification patch in progress: #49 
- Chromium implementation issue: https://crbug.com/982379 - which is also running an [Origin Trial](https://developers.chrome.com/origintrials/#/view_trial/-8986933056417824767)

**Comment by binoculars88** [comment]
@scheib our users started reporting a bug with pointerlock a few days ago. It seems it started around the 28th of May. Could this be related to the release of Chrome 83? A bit more info on the bug being reported: We have a window saying the pointer isn't locked when that's the case. When users click the window we request a pointerlock again. Never had any issues, but since a couple of days, users complain the window won't go away. We can't consistently reproduce this ourselves, but in the rare case where we see this too, we notice the function gets called but for some reason, the pointer doesn't lock. From that moment on, the Chrome tab seems "broken" and even when refreshing in Incognito, pointerlock will always fail. Only trying it in a new Chrome tab locks the pointer again. 

We don't have a lot to go from atm, as we can't reproduce consistently, but I wanted the share this already. The bug is there for sure. We have a very active community, never had bug reports regarding this, but the last days it's one after the other. We haven't made any changes on our side. 

We will continue doing tests in the next couple of days. I'll keep you posted if we find something more concrete.

Note: we use `requestPointerLock()`, not the new `requestPointerLock({unadjustedMovement: true})`

**Comment by scheib** [comment]
@binoculars88 It may be related.  This forum is for the spec change.  Please file a new crbug.com and post a comment on https://crbug.com/982379 indicating that it may be related and we'll take a look.  A repro case would help significantly.

**Comment by JamesHollyer** [comment]
@smaug---- We have successfully implemented this feature on all Platforms. It is now in Origin Trial and being used by Stadia and Nvidia's Geforce Now. Do you think Mozilla would support implementing this feature now that it is possible on all platforms and starting to get adoption?

**Comment by nondebug** [comment]
> Based on some feedback, implementing this properly on all the platforms can be tricky. Linux for example has several ways to control acceleration. And I'm not sure even about MacOS.

@smaug---- Chrome implements the option on Windows, macOS, and Chrome OS. On Windows and macOS we don't need to modify any system-wide settings.

**Windows**: Use the [Raw Input](https://docs.microsoft.com/en-us/windows/win32/inputdev/raw-input) API to receive WM_INPUT notifications. [RAWMOUSE](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawmouse) contains linear unaccelerated pointer data.

**macOS**: Read CGEvent's kCGEventUnacceleratedPointerMovementX and kCGEventUnacceleratedPointerMovementY fields which are populated on 10.14+ but only declared in the SDK starting from 10.15.1.

No solution for Linux yet.

**Comment by smaug----** [comment]
So what does Chrome do then on Linux? Does it not expose unadjustedMovement at all in the dictionary or how can one do feature detection?

**Comment by mustaqahmed** [comment]
On Linux, Chrome rejects the promise (and [throws an exception](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/page/pointer_lock_controller.cc;drc=860d35b9034b71187a24e7519b1ca7a2814fa00d;l=231)) only when the pointer-lock request is made with `{unadjustedMovement:true}`.
