### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#50]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue w3c/uievents#19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
@NavidZ, we are looking forward to seeing you at TPAC. Any chance you could provide some details  for the above questions?

**Comment by NavidZ** [comment]
@marcoscaceres Thanks for pinging me on the issue. I guess I missed it before. Here is the update:

> What progress has your spec made in the last 12 months?

Aside from some editorial changes and whatnot, we have started adding a new capability to the request API so that it matches more platform like features such as disabling mouse acceleration. We are still working on it to get more feedback from other vendors and also investigate how different underlying platforms could support the feature.
Aside from this new feature we wanted to clear the coordinate space for some of the attributes as part of this [issue](https://github.com/w3c/pointerlock/issues/42) but we didn't make much progress on that due to the lack of feedback from others and some oppositions on more aggressive changes in the early [proposals](https://github.com/w3c/pointerevents/issues/607).

> Is anything blocking your spec from moving to CR?

Nothing actually. I believe we should be okay if we land the new capability above and also hopefully rewrite parts of the spec to make it more like a procedural/algorithmic spec it should be ready to go for V2. If we could also clear the coordinate space in this [issue](https://github.com/w3c/pointerlock/issues/42) for V2 that will be fantastic.

> What do you want to achieve for your spec in the next two days (of breakout sessions)?

Although the discussions are already happening on the [issue](https://github.com/w3c/pointerlock/issues/36) if anyone has any comment I'd love to hear in person. I do like to hear if other vendors have heard any new requirements that we might need to address in V2.
