### ISSUE TITLE
User gesture requirement allows for abuse.

### ISSUE THREAD

**Issue by JamesHollyer** [w3c/pointerlock#59]
Websites can stop users from navigating away from the site by using something like:
document.onmousemove = function(){lock_element.requestPointerLock();};
This is a terrible user experience. While it is easy enough to use shortcuts to close the tab or something like that many novice users will feel stuck and get frustrated hitting escape only to get locked again.  

Could we change the requirement to be a bit more strict than simply user gesture? I propose we either disallow mouse movement or specifically require a click instead of just a generic user gesture.

Another solution might be to only allow a certain number of re-requests before prompting the user?

Thoughts?

**Comment by marcoscaceres** [comment]
Firefox seems to have some mitigations in place:

> Request for pointer lock was denied because Element.requestPointerLock() was not called from inside a short running user-generated event handler, and the document is not in full screen.

**Comment by marcoscaceres** [comment]
Would it make sense to restrict pointerlock to fullscreen? We do have somewhat similar constraints in the screen orientation API.

**Comment by scheib** [comment]
Pointer lock should not be possible without a user gesture.  If the web app
is rapidly lock/unlocking then the exit instructions should stay visible
(if not, file a bug on whichever browsers).  If the user presses ESC then
it web app is not allowed to relock, because there hasn't been a user
gesture.  If that is happening, again file a browser bug.

I don't think there's a spec issue here, unless I'm confused?  The user
gesture requirement is precisely what should be preventing this malicious
pattern.

>

**Comment by NavidZ** [comment]
I agree with @scheib . User gesture should suffice for the use case. @JamesHollyer I don't think your code would work in Chrome the last time I was checking that. User activation is like a user click or something like that. Only a mouse move is not considers activation. This is more or less the same guard that let the app open a popup. Without user activation they cannot open a popup either.

**Comment by JamesHollyer** [comment]
Turns out User Gesture does not include mouse movement and this is a chrome bug.  Closing the issue.
