### ISSUE TITLE
Status report and planning for TPAC 2021

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#75]
[TPAC](https://www.w3.org/2021/10/TPAC/#schedule) will be virtual again this year. There will be a WebApps WG meeting at some point between 24 and 29 October.

There are two things we need you to do in the meantime:
1. Let @marcoscaceres  and I know before 17 September if you plan to hold a specification specific meeting (in addition to the general WebApps WG meeting)
2. Post a specification status report before 30 September

Your specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

CC @siusin

**Comment by reillyeon** [comment]
I recommend discussing the status of https://github.com/w3c/pointerlock/pull/49. CC @nondebug.

**Comment by marcoscaceres** [comment]
Reminder that the WG is meeting on [Tuesday 26 October 2021](https://github.com/w3c/webappswg/wiki/TPAC-2021#agenda---general-meeting), 9PM to 11PM UTC. 

It would great if someone could give an 5 minute update on the state of this spec.

**Comment by nondebug** [comment]
I can summarize the current state of the spec along with the status on PR #49

**Comment by mustaqahmed** [comment]
Thanks @nondebug for covering un-accelerated `movementX/Y` part.  I will provide a quick update on the overall state plus last year's changes.

**Comment by marcoscaceres** [comment]
Thanks you both! See you tomorrow.

**Comment by mustaqahmed** [comment]
### Spec changes since TPAC 2020
*   One normative change: [PR#68](https://github.com/w3c/pointerlock/pull/68) switched `movementX/Y` coordinates from integer type (`long`) to floating-point (`double`), to match CSSOM View Module [MouseEvent extension](https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface).
    *   This was the first step towards a bigger goal: allow precise movement tracking with fractional `screenX/Y` on high resolution screens (more precisely, screens with high [device pixel ratio](https://developer.playcanvas.com/en/user-manual/optimization/runtime-devicepixelratio)).
    *   Next stop: exposing floating-point `movementX/Y` values only in PointerEvents.  Also related [Issue #42](https://github.com/w3c/pointerlock/issues/42).
*   Quite a few editorial cleanups, thanks to [@marcoscaceres](https://github.com/marcoscaceres).

### Outstanding changes
*   [Issue #67](https://github.com/w3c/pointerlock/issues/67): remove redundant user activation definition because HTML already defines it.
    *   Work in progress, planning [this](https://github.com/w3c/pointerlock/pull/70#issuecomment-912772669) cleanup after landing a blocking [HTML change](https://github.com/whatwg/html/pull/7248).
*   [Issue #36](https://github.com/w3c/pointerlock/issues/36): supporting unaccelerated movement for a better gaming experience.
    *   [PR#49](https://github.com/w3c/pointerlock/pull/49) needs commitments from other browsers!
    *   Chrome is done with implementation behind a flag, and also with origins trials with Stadia and Nvidia's Geforce Now.  Currently blocked by the spec change above. Bug: [982379](https://bugs.chromium.org/p/chromium/issues/detail?id=982379).
    *   [Firefox asked](https://github.com/w3c/pointerlock/issues/36#issuecomment-526542010) about handling OS-specific challenges around system-wide settings, and [Chrome found solutions](https://github.com/w3c/pointerlock/issues/36#issuecomment-951444364) for almost all cases.
