### ISSUE TITLE
TPAC 2022 status report

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#80]
[TPAC 2022 ](https://www.w3.org/2022/09/TPAC/) is hybrid this year. WebApps will meet in Vancouver on [12 and 13 September](https://www.w3.org/calendar/tpac2022/). Please [register](https://www.w3.org/2022/09/TPAC/registration.html) if you plan to attend in person or remotely.

Editors, we need you to do two things before 30 August 2022:

1. If you want agenda time to discuss your spec(s), please use W3C/webappswg#87 to request it
2. Complete a status report for your spec(s)

#### Status report

Your status report should answer these questions (as a comment on this issue):

1. What progress has your spec made in the last 12 months?
2. Is anything blocking your spec from moving to CR/Rec?
3. If yes, what is your plan to unblock it and do you need any help?

Please post a status report on your spec(s) even if you do not plan to attend TPAC at all.

CC @marcoscaceres and @siusin

**Comment by mustaqahmed** [comment]
### Spec changes since TPAC 2021
- One normative change: [PR #76](https://github.com/w3c/pointerlock/pull/76) gets rid of “engagement gestures” in this spec in favor of “User Activation” in the HTML spec ([Sec 6.4 Tracking user activation](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation)).  The “engagement gestures” details were both incomplete and redundant after the HTML spec was updated a few years ago.  The two spec are now fully in-sync: all the details now belong to HTML, with `requestPointerLock` simply marked as a "transient activation-gated API".
- Lots of editorial cleanups, thanks to Marcos Cáceres ([@marcoscaceres](https://github.com/marcoscaceres)), Dominique Hazael-Massieux ([@dontcallmedom](https://github.com/dontcallmedom)) and Xiaoqian Wu ([@siusin](https://github.com/siusin)).

### Outstanding issues
- [Issue #25](https://github.com/w3c/pointerlock/issues/25) about Working Draft
  - [W3C Working Draft](https://www.w3.org/TR/pointerlock/) and [W3C Editor's Draft](https://w3c.github.io/pointerlock/) both point to 08 July 2022 version.
  - Perhaps an easy question for spec experts: do we still need the distinction?  Is the issue still relevant?
- [Issue #74](https://github.com/w3c/pointerlock/issues/74) MovementX/Y values in “coalesced events”
  - Spec overlap with PointerEvents, and PEWG decided that it does not belong there!
- [Issue #36](https://github.com/w3c/pointerlock/issues/36) Supporting unaccelerated movement for a better gaming experience.
  - [PR#49](https://github.com/w3c/pointerlock/pull/49) _still_ needs other browsers’ commitments!
  - We need to get out of this [unfortunate situation](https://github.com/w3c/pointerlock/pull/49#issuecomment-1041005606): Chrome [shipped](https://groups.google.com/a/chromium.org/g/blink-dev/c/cQn7OwcMQ64/m/uDi7C5oiAgAJ) to support Stadia and Nvidia Geforce Now while facing lack of response.
  - [Mozilla raised](https://github.com/w3c/pointerlock/issues/36#issuecomment-526542010) the concern about OS-specific challenges around system-wide settings.  Does [our response ](https://github.com/w3c/pointerlock/issues/36#issuecomment-951444364)look good for that (modulo the Linux case)?
  - Chrome bug: [982379](https://bugs.chromium.org/p/chromium/issues/detail?id=982379).

**Comment by mustaqahmed** [comment]
Past requests for position that need attention:
- https://lists.webkit.org/pipermail/webkit-dev/2020-October/031473.html
- https://github.com/mozilla/standards-positions/issues/448
